backend:
  name: git-gateway
  branch: master

# publish_mode: editorial_workflow # Allows draft modde

media_folder: "/public/uploads" # Folder to upload media to. Relative to repo base
public_folder: "/uploads" # src folder for uploaded media. Relative to Prouction site

collections:
  - name: "products"
    label: 'Products'
    folder: "src/content/products"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widjet: "string"
      - label: "Description"
        name: "description"
        widjet: "text"
      - label: "Image"
        name: "image"
        widjet: "image"
        choose_url: true
      - label: "Price"
        name: "price"
        widjet: "string"